Update casr.yml

diff --git a/.github/workflows/casr.yml b/.github/workflows/casr.yml
--- a/.github/workflows/casr.yml
+++ b/.github/workflows/casr.yml
@@ -36,7 +36,12 @@ jobs:
         ./gradlew clean build -x test
     - name: Run CASR
       run: |
-        find . -name '*.jar' -exec sh -c 'echo "Processing {}" && timeout 1000s casr-java -o {}.casrep -- java -jar {}' \;
+        find . -name '*.jar' -exec sh -c '
+          for jarfile; do
+            echo "Processing $jarfile"
+            timeout 60s casr-java -o "$jarfile.casrep" -- java -jar "$jarfile" || echo "Failed to process $jarfile" >> error.log
+          done
+        ' sh {} +    
     - name: List any casr reports created
       run: |
         find . -type f -name "*.casrep"
